Notebook для практики по дисциплине "Методы машинного обучения"
Выполнили студенты:
- Баймухамедов Рафаэль Русланович
- Аршин Александр Дмитриевич
- Пасечный Леонид Витальевич

Преподаватель
- Петруша Полина Георгиевна

Скачаем датасет с Яндекс.Диска

In [55]:
import requests
from urllib.parse import urlencode

base_url = 'https://cloud-api.yandex.net/v1/disk/public/resources/download?'
public_key = "https://disk.yandex.ru/d/V1sJpR-SUJ_b8A"

final_url = base_url + urlencode(dict(public_key=public_key))
response = requests.get(final_url)
download_url = response.json()['href']

download_response = requests.get(download_url)
with open('dataset.xlsx', 'wb') as f:
    f.write(download_response.content)

Прочитаем в датафрейм наш файл

In [57]:
from pathlib import Path
import pandas as pd

xlsx_path = "dataset.xlsx"
if not xlsx_path:
    raise FileNotFoundError("xlsx файл не найден")
print("Найден XLSX:", xlsx_path)

df = pd.read_excel(xlsx_path, sheet_name=0, header=[0,1])
print("Данные загружены в df")

Найден XLSX: dataset.xlsx
Данные загружены в df

Настроим pandas

In [58]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

Посмотрим на датафрейм

In [59]:
df.head()

                                                                                                                      Unnamed: 0_level_0  \
                                                                                                                            Наименование
0                                                    биологически активная добавка к пище "ВитаФин" ("VitaFin") (таблетки массой 700 мг)
1                                               биологически активная добавка к пище "Гепаплант" ("Hepaplant") (таблетки массой 1000 мг)
2  биологически активная добавка к пище "Фемибион ® Наталкер I" ("Femibion® Natalcare I") (таблетки массой 609 мг±3% покрытые оболочкой)
3                                 биологически активная добавка к пище "Неогален (Neogalen). СЛИМ КОД. Комплекс" (капсулы массой 500 мг)
4                                                                   биологически активная добавка к пище "КРЕСТИНОЛ" (капсулы по 350 мг)

                                                                                                                                                                                                                                                                                                                      Unnamed: 1_level_0  \
                                                                                                                                                                                                                                                                                                                            Изготовитель
0                                                                                                                                                                                                                                                    Ханкинтатукку Оу" ("Hankintatukku Oy"), Lehtolankatu 18, 03600 Karkkila (Финляндия)
1                                                                                                                                                                                                                                                    Ханкинтатукку Оу" ("Hankintatukku Oy"), Lehtolankatu 18, 03600 Karkkila (Финляндия)
2  "Мерк КгаА энд Ко Верк Шпитталь", Хёссельгассе 20, А- 9800 Шпитталь/Драу, Австрия или "Никомед Фарма Сп. з.о.о.", Ал. Иерозолимские 146 А, 02-305, Варшава, Польша под контролем "Мерк Зельбстмедикацион ГмбХ, Pёсслерштрассе, 96, 64293 Дармштадт ("Merck Selbstmedikation GmbH", Rosslerstrasse 96, 64293 Darmstadt) (ФРГ) Германия
3                                                                                                                                  продукция изготовлена ООО "КоролёвФарм", 121609, г. Москва, ул. Крылатские холмы, д.1, кв.422 (адрес производства: 141070, Московская область, г.Королёв, ул. Пионерская, д.4) (Российская Федерация)
4                                                                                                                                                                                                                                                   ЗАО "Пекталь", 193019, г. Санкт-Петербург, ул. Бехтерева, д.1 (Российская Федерация)

                              Unnamed: 2_level_0  \
                      Номер свидетельства и дата
0   RU.77.99.11.003.Е.000894.09.10 от 10.09.2010
1   RU.77.99.11.003.Е.000895.09.10 от 10.09.2010
2  RU.77.99.11.003.Е.000886.09.10 от 10.09.2010
3   RU.77.99.11.003.Е.001040.09.10 от 14.09.2010
4   RU.77.99.11.003.Е.001573.10.10 от 05.10.2010

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Unnamed: 3_level_0  \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Этикетка
0  Рекомендации по применению: взрослым по 1-2 таблетки в день во время еды. Продолжительность приема - 1-2 месяца. При необходимости прием можно повторить. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Лицам с заболеваниями щитовидной микроэлементыы рекомендуется проконсультироваться с врачом-эндокринологом. Срок годности - 3 года. Хранить в сухом, недоступном для детей месте, при температуре не выше 25°С.
1                                                                                                       Рекомендации по применению: взрослым по 1 таблетке 2-3 раза в день во время еды. Продолжительность приема - 1-2 месяца. При необходимости прием можно повторить. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Срок годности - 3 года. Хранить в сухом, недоступном для детей месте, при температуре не выше 25°С.
2                                                                                                                               Рекомендации по применению: женщинам, планирующим беременность, и беременным до конца 12-й недели беременности по 1 таблетке 1 раз в день во время еды, запивая водой. Срок годности - 24 месяца. Хранить в сухом, недоступном для детей месте при температуре не выше 25°С. Противопоказания: индивидуальная непереносимость компонентов. Перед применением рекомендуется проконсультироваться с врачом.
3                                                                                                                                Рекомендации по применению: взрослым по 1 капсуле 3 раза в день во время еды. Продолжительность приема - 1 месяц. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Срок годности - 2 года. Хранить в сухом, защищенном от света и недоступном для детей месте, при температуре не выше 25°С.
4                                Рекомендации по применению: взрослым по 1 капсуле 1 раз в день во время еды. Продолжительность приема - 20 дней. После 10 дневного перерыва рекомендуется повторный прием. Возможны повторные приемы в течение года. Срок годности - 2 года. Хранить в сухом, защищенном от света и недоступном для детей месте, при температуре не выше 25°С. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением необходимо проконсультироваться с врачом.

  Unnamed: 4_level_0  \
       Происхождение
0        иностранное
1        иностранное
2        иностранное
3      отечественное
4      отечественное

                                                           Unnamed: 5_level_0  \
                                                             Противопоказания
0  индивидуальная непереносимость компонентов, беременность, кормление грудью
1  индивидуальная непереносимость компонентов, беременность, кормление грудью
2                                  индивидуальная непереносимость компонентов
3  индивидуальная непереносимость компонентов, беременность, кормление грудью
4  индивидуальная непереносимость компонентов, беременность, кормление грудью

  Unnamed: 6_level_0 Unnamed: 7_level_0           Unnamed: 8_level_0  \
       Срок годности    Год регистрации Количество групп компонентов
0             3 года               2010                            3
1             3 года               2010                        много
2             2 года               2010                            2
3             2 года               2010                        много
4             2 года               2010                        много

                                  Пищевые вещества                         \
  Витамины, витаминоподобные вещества и коферменты Макро- и микроэлементы
0                                              вит               элементы
1                                              вит                    NaN
2                                              вит               элементы
3                                              вит                    NaN
4                                              вит                    NaN

                                                \
  Жиры, жироподобные вещества и их производные
0                                          NaN
1                                         пнжк
2                                          NaN
3                                          NaN
4                                          NaN

                                                      \
  Белки, пептиды, аминокислоты,  нуклеиновые кислоты
0                                                NaN
1                                                NaN
2                                                NaN
3                                       аминокислоты
4                                                NaN

  Минорные компоненты растений            \
          Фенольные соединения Алкалоиды
0                      фенольн       NaN
1                      фенольн       NaN
2                          NaN       NaN
3                      фенольн       NaN
4                      фенольн       NaN

  Пробиотики в монокультурах и ассоциациях   \
              Пробиотические микроорганизмы
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN

                    Пищевые вещества Минорные компоненты растений             \
  Углеводы и продукты их переработки                     Сапонины Терпеноиды
0                                NaN                          NaN        NaN
1                                NaN                          NaN        NaN
2                                NaN                          NaN        NaN
3                                NaN                          NaN        NaN
4                                NaN                          NaN        NaN

                                                                              \
  Естественные метаболиты и стимуляторы метаболизма Гидроксикоричные кислоты
0                                               NaN                      NaN
1                                               NaN              гидроксикор
2                                               NaN                      NaN
3                                               ест                      NaN
4                                               ест                      NaN

                               \
  Ферменты Дубильные вещества
0      NaN                NaN
1      NaN                NaN
2      NaN                NaN
3      NaN                NaN
4      NaN                дуб

  Минеральные и минерало-органические природные субстанции  \
                                Цеолиты\nГуминовые кислоты
0                                                      NaN
1                                                      NaN
2                                                      NaN
3                                                      NaN
4                                                      NaN

                                      Система органов  \
  для беременных, кормящих и планирующих беременность
0                                                 NaN
1                                                 NaN
2                                          беременные
3                                                 NaN
4                                                 NaN

                                                             \
  костно-мышечная сиситема нервная система иммунная система
0                      NaN             NaN        иммунитет
1                      NaN             NaN              NaN
2                      NaN             NaN              NaN
3                      NaN             NaN              NaN
4                      NaN             NaN              NaN

                                                             \
  пищеварительный тракт и обмен веществ мочеполовая система
0                                   NaN                 NaN
1                                   NaN                 NaN
2                                   NaN                 NaN
3                                   жкт                 NaN
4                                   NaN               почки

                                                                   \
  дерматологические БАД органы чувств сердечно-сосудистая система
0                   NaN           NaN                         NaN
1                   NaN           NaN                         NaN
2                   NaN           NaN                         NaN
3                   NaN           NaN                         NaN
4                   NaN           NaN                         NaN

                                                                     \
  противоопухолевые БАД противопаразитарные БАД дыхательная система
0                   NaN                     NaN                 NaN
1                   NaN                     NaN                 NaN
2                   NaN                     NaN                 NaN
3                   NaN                     NaN                 NaN
4                   NaN                     NaN                 NaN

                                                                    \
  кровь и система кроветворения противомикробные БАД Форма выпуска
0                           NaN                  NaN      таблетки
1                           NaN                  NaN      таблетки
2                           NaN                  NaN      таблетки
3                           NaN                  NaN       капсулы
4                           NaN                  NaN       капсулы

                                                                    \
  Продолжительность приема Происхождение (природное/синтетическое)
0               1-2 месяца                Природное (растительное)
1               1-2 месяца                Природное (растительное)
2                9 месяцев                           Синтетическое
3          1 месяц и менее                Природное (растительное)
4          1 месяц и менее                Природное (растительное)

                                                                                                                                                                                                                                                                                                                                                                                                                        \
                                                                                                                                                                                                                                                                                                                                                                           Сырье (растительное/животное/биологическое)
0                                                                                                                                                                                                                                                                                          Экстракта зелёного чая (Camellia sinensis - Камелия китайская), экстракт кожицы винограда (Винный виноград - Vitis Vinifera
1                                                                                                                                                                                                                                                                                          Экстракта зелёного чая (Camellia sinensis - Камелия китайская), экстракт кожицы винограда (Винный виноград - Vitis Vinifera
2                                                                                                                                                                                                                                                                                                                                                                                                                  NaN
3                                                                                                                                                                                    Экстракт травы гарцинии камбоджийской (Garcīnia gūmmi-gūtta - Гарци́ния камбоджи́йская), экстракт листьев матэ (Падуб парагва́йский - Ilex paraguariénsis), экстракт виноградных косточек, алоэ вера гель (Алоэ вера - Aloë vera)
4  Экстракт брокколи (Капуста огородная - Brassica oleracea), экстракт сои (Соя культурная - Glycine max), экстракт листьев бадана (Бадан толстолистный - Bergenia crassifolia), экстракт корней дягиля лекарственного (Дягиль лекарственный - Angеlica archangelica) , экстракт корней цимицифуги (Клопогон кистевидный - Cimicifuga racemosa), экстракт травы боровой матки (Орти́лия однобо́кая - Orthília secúnda)

        Группа населения                                                   \
  предназначен для детей возраст детей предназначен для взрослых      пол
0                    NaN           NaN                  взрослые      NaN
1                    NaN           NaN                  взрослые      NaN
2                    NaN           NaN                  взрослые  женщины
3                    NaN           NaN                  взрослые      NaN
4                    NaN           NaN                  взрослые      NaN


  пожилые
0     NaN
1     NaN
2     NaN
3     NaN
4     NaN

Соединим заголовки первого и второго уровня вместе. Также уберем пробелы между словами в столбцах, заменив их на "_" и приведем названия столбцов к нижнему регистру.

In [60]:
import re
from collections import Counter, defaultdict

def clean(s):
    if s is None: return ""
    s = str(s).replace("\n"," ").replace("\xa0"," ").strip()
    return re.sub(r"\s+"," ", s)

flat = []
for top, sub in df.columns:
    top, sub = clean(top), clean(sub)
    name = sub if (not top or top.lower().startswith("unnamed")) else f"{top}__{sub}" if sub else top
    name = name.replace("ё","е")
    name = re.sub(r"\s+", "_", name)
    name = re.sub(r"[\\/:;,\"'()]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    name = name.lower()
    flat.append(name)

cnt = Counter(flat); seen = defaultdict(int); uniq = []
for n in flat:
    seen[n] += 1
    uniq.append(n if cnt[n] == 1 else f"{n}__{seen[n]}")

df.columns = uniq

Переименуем некоторые столбцы

In [61]:
to_rename = {
    "пищевые_вещества_макро-_и_микроэлементы": "пищевые_вещества_макро_и_микроэлементы",
    "минеральные_и_минерало-органические_природные_субстанции_цеолиты_гуминовые_кислоты":"минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты",
    "система_органов_костно-мышечная_сиситема": "система_органов_костно_мышечная_система",
    "система_органов_форма_выпуска":"форма_выпуска",
    "система_органов_продолжительность_приема":"продолжительность_приема",
    "система_органов_происхождение":"происхождение",
    "система_органов_сырье_растительное_животное_биологическое":"сырье",
    "система_органов_сердечно-сосудистая_система":"система_органов_сердечно_сосудистая_система"
}

df = df.rename(columns=to_rename)

Создаем 2 новых столбца:
- Рекомендации по применению
- Продолжительность приема

Информацию для них берем из столбца Этикетка, затем отчищаем оттуда взятую инфу.

In [62]:
df['рекомендации_по_применению'] = 'a'
df['продолжительность_приема'] = 'b'

for row in range(len(df)):
  string = str(df.at[row, 'этикетка'])

  dot = string.find(".")+1
  str_for_et = str(df.at[row, 'этикетка'])[string.find(".", dot)+1::]

  value_1 = string[string.find("Рекомендации по применению: ")+len("Рекомендации по применению: "):dot]
  df.at[row, 'рекомендации_по_применению'] = value_1

  value_2 = string[string.find("Продолжительность приема - ")+len("Продолжительность приема - "):string.find(".", dot)]
  df.at[row, 'продолжительность_приема'] = value_2

  df.at[row, 'этикетка'] = str_for_et

Срок годности преобразуем из лет в месяцы

Посмотрим уникальные значения до изменений

In [63]:
print(df['срок_годности'].unique())

['3 года' '2 года' '1 год' '4 года' '1,5 года' '1 год, 2 года' '8 месяцев'
 '2 года, 1 год' '2,5 месяца' '5 лет' '1 месяц' '2 месяца' '19 месяцев'
 '28 месяцев' '1 год, 2 месяца' '3,5 года' '6 месяцев' '2,5 года'
 '32 месяца' '21 месяц' '14 месяцев' '3 месяца' '2 года, 1,5 года'
 '15 суток' '11 месяцев' '20 месяцев' '25 месяцев']

In [64]:
bad_val = {"1 год, 2 года" : 24,
           "1 год, 2 месяца": 14,
           "1,5 года": 18,
           "15 суток": 0.5,
           "2 года": 24,
           "2 года, 1 год": 24,
           "2 года, 1,5 года": 24,
           "2,5 года": 30,
           "3 года": 36,
           "3,5 года": 42,
           "4 года": 48,
           "5 лет": 60,
           "1 год": 12
           }
for row in range(len(df)):
  val = str(df.at[row, 'срок_годности'])
  if val in bad_val.keys():
    df.at[row, 'срок_годности'] = bad_val[val]
  else:
    if ('меся' in str(df.at[row, 'срок_годности'])):
      string = str(df.at[row, 'срок_годности'])
      str_res = string[:string.index(" ")]
      if (str_res != ''):
        if (',' in str(df.at[row, 'срок_годности'])):
          str_res = str_res.replace(',', '.')
        df.at[row, 'срок_годности'] = float(str_res)

Посмотрим уникальные значения после (Все преобразовалось)

In [65]:
print(df['срок_годности'].unique())

[36 24 12 48 18 8.0 2.5 60 1.0 2.0 19.0 28.0 14 42 6.0 30 32.0 21.0 3.0
 0.5 11.0 20.0 25.0]

Также меняем столбец "возраст_детей". Меняем года на месяцы
Будет указано одно значение (12 например). Оно будет означать, что для детей от 12 месяцев.

In [66]:
bad_val = {"от 11 лет" : 132,
           "от 12 лет": 144,
           "от 14 лет": 168,
           "от 3 месяцев": 3,
           "от 7 лет": 84,
           "с рождения": 0,
           "от 1,5 лет": 24,
           "от 3 лет": 36,
           "от 4 лет": 48,
           "от 5 лет": 60,
           "от 1 года": 12
           }
for i in range(len(df)):
  val = str(df.at[i, 'группа_населения_возраст_детей'])
  if val in bad_val.keys():
    df.at[i, 'группа_населения_возраст_детей'] = bad_val[val]
print(df['группа_населения_возраст_детей'].unique())

[nan 132 84 0 168 36 48 144 3 12 24 60]

Исправим орфографические ошибки в строках

Посмотрим на уникальные значения в некоторых столбцах

In [67]:
print(df["пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты"].unique())
print(df["минорные_компоненты_растений_алкалоиды"].unique())
print(df["пищевые_вещества_углеводы_и_продукты_их_переработки"].unique())
print(df["минорные_компоненты_растений_гидроксикоричные_кислоты"].unique())
print(df["минорные_компоненты_растений_ферменты"].unique())
print(df["минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты"].unique())
print(df["система_органов_для_беременных_кормящих_и_планирующих_беременность"].unique()),
print(df["система_органов_костно_мышечная_система"].unique()),
print(df["система_органов_нервная_система"].unique()),
print(df["система_органов_иммунная_система"].unique()),
print(df["система_органов_дерматологические_бад"].unique()),
print(df["система_органов_сердечно_сосудистая_система"].unique()),
print(df["система_органов_противопаразитарные_бад"].unique()),
print(df["система_органов_дыхательная_система"].unique()),
print(df["система_органов_противомикробные_бад"].unique())

[nan 'аминокислоты' 'аминоксилоты']
[nan 'алкалоид' 'алкалоиды' 'алкалод']
[nan 'полисахариды' 'полисахарилы' 'полисахарид' 'полисхариды']
[nan 'гидроксикор' 'гидрокор']
[nan 'ферменты' 'фермент']
[nan 'цеолиты' 'цеолит']
[nan 'беременные' 'берем']
[nan 'суставы' 'суст' 'суств']
[nan 'нервная' 'неврная' 'нерврная' 'нерв' 'невр']
['иммунитет' nan 'иммун' 'имм' 'имммун']
[nan 'кожа' 'коэа']
[nan 'сердце' 'серд']
[nan 'паразиты' 'паразит']
[nan 'легкие' 'кашель' 'легк' 'дых']
[nan 'бакт' 'бактер' 'грию' 'вирус' 'гриб' 'вир']

Напишем функцию, которая заменяет значение из списка в строке столбца на заданное значение

In [68]:
def replace_exact(df, col, variants, target):
    df.loc[df[col].isin(variants), col] = target

pairs = [
    ["пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты", ["аминоксилоты"], "аминокислоты"],
    ["минорные_компоненты_растений_алкалоиды", ["алкалод", "алкалоид"], "алкалоиды"],
    ["пищевые_вещества_углеводы_и_продукты_их_переработки", ["полисахарид", "полисахарилы", "полисхариды"], "полисахариды"],
    ["минорные_компоненты_растений_гидроксикоричные_кислоты", ["гидрокор"], "гидроксикор"],
    ["минорные_компоненты_растений_ферменты", ["фермент"], "ферменты"],
    ["минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты", ["цеолит"], "цеолиты"],
    ["система_органов_для_беременных_кормящих_и_планирующих_беременность", ["берем"], "беременные"],
    ["система_органов_костно_мышечная_система", ["суст", "суств"], "суставы"],
    ["система_органов_нервная_система", ["невр", "неврная", "нерврная", "нерв"], "нервная"],
    ["система_органов_иммунная_система", ["имм", "имммун", "иммун"], "иммунитет"],
    ["система_органов_дерматологические_бад", ["коэа"], "кожа"],
    ["система_органов_сердечно_сосудистая_система", ["серд"], "сердце"],
    ["система_органов_противопаразитарные_бад", ["паразит"], "паразиты"],
    ["система_органов_дыхательная_система", ["легк"], "легкие"],
    ["система_органов_противомикробные_бад", ["бакт", "бактер"], "бактерия"],
    ["система_органов_противомикробные_бад", ["вир"], "вирус"],
    ["система_органов_противомикробные_бад", ["вир"], "вирус"],
    ["система_органов_противомикробные_бад", ["грию"], "гриб"]
]

for i in range(len(pairs)):
    replace_exact(df, pairs[i][0],pairs[i][1], pairs[i][2])

Проверим теперь уникальные значения этих же столбцов

In [69]:
print(df["пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты"].unique())
print(df["минорные_компоненты_растений_алкалоиды"].unique())
print(df["пищевые_вещества_углеводы_и_продукты_их_переработки"].unique())
print(df["минорные_компоненты_растений_гидроксикоричные_кислоты"].unique())
print(df["минорные_компоненты_растений_ферменты"].unique())
print(df["минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты"].unique())
print(df["система_органов_для_беременных_кормящих_и_планирующих_беременность"].unique()),
print(df["система_органов_костно_мышечная_система"].unique()),
print(df["система_органов_нервная_система"].unique()),
print(df["система_органов_иммунная_система"].unique()),
print(df["система_органов_дерматологические_бад"].unique()),
print(df["система_органов_сердечно_сосудистая_система"].unique()),
print(df["система_органов_противопаразитарные_бад"].unique()),
print(df["система_органов_дыхательная_система"].unique()),
print(df["система_органов_противомикробные_бад"].unique())

[nan 'аминокислоты']
[nan 'алкалоиды']
[nan 'полисахариды']
[nan 'гидроксикор']
[nan 'ферменты']
[nan 'цеолиты']
[nan 'беременные']
[nan 'суставы']
[nan 'нервная']
['иммунитет' nan]
[nan 'кожа']
[nan 'сердце']
[nan 'паразиты']
[nan 'легкие' 'кашель' 'дых']
[nan 'бактерия' 'гриб' 'вирус']

Посмотрим как выглядит датафрейм на данный момент

In [70]:
df.head()

,наименование,изготовитель,номер_свидетельства_и_дата,этикетка,происхождение,противопоказания,срок_годности,год_регистрации,количество_групп_компонентов,пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты,пищевые_вещества_макро_и_микроэлементы,пищевые_вещества_жиры_жироподобные_вещества_и_их_производные,пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты,минорные_компоненты_растений_фенольные_соединения,минорные_компоненты_растений_алкалоиды,пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы,пищевые_вещества_углеводы_и_продукты_их_переработки,минорные_компоненты_растений_сапонины,минорные_компоненты_растений_терпеноиды,минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма,минорные_компоненты_растений_гидроксикоричные_кислоты,минорные_компоненты_растений_ферменты,минорные_компоненты_растений_дубильные_вещества,минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты,система_органов_для_беременных_кормящих_и_планирующих_беременность,система_органов_костно_мышечная_система,система_органов_нервная_система,система_органов_иммунная_система,система_органов_пищеварительный_тракт_и_обмен_веществ,система_органов_мочеполовая_система,система_органов_дерматологические_бад,система_органов_органы_чувств,система_органов_сердечно_сосудистая_система,система_органов_противоопухолевые_бад,система_органов_противопаразитарные_бад,система_органов_дыхательная_система,система_органов_кровь_и_система_кроветворения,система_органов_противомикробные_бад,форма_выпуска,продолжительность_приема,система_органов_происхождение_природное_синтетическое,сырье,группа_населения_предназначен_для_детей,группа_населения_возраст_детей,группа_населения_предназначен_для_взрослых,группа_населения_пол,группа_населения_пожилые,рекомендации_по_применению
0,"биологически активная добавка к пище ""ВитаФин"" (""VitaFin"") (таблетки массой 700 мг)","Ханкинтатукку Оу"" (""Hankintatukku Oy""), Lehtolankatu 18, 03600 Karkkila (Финляндия)",RU.77.99.11.003.Е.000894.09.10 от 10.09.2010,"При необходимости прием можно повторить. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Лицам с заболеваниями щитовидной микроэлементыы рекомендуется проконсультироваться с врачом-эндокринологом. Срок годности - 3 года. Хранить в сухом, недоступном для детей месте, при температуре не выше 25°С.",иностранное,"индивидуальная непереносимость компонентов, беременность, кормление грудью",36,2010,3,вит,элементы,NaN,NaN,фенольн,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,иммунитет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,таблетки,1-2 месяца,Природное (растительное),"Экстракта зелёного чая (Camellia sinensis - Камелия китайская), экстракт кожицы винограда (Винный виноград - Vitis Vinifera",NaN,NaN,взрослые,NaN,NaN,взрослым по 1-2 таблетки в день во время еды.
1,"биологически активная добавка к пище ""Гепаплант"" (""Hepaplant"") (таблетки массой 1000 мг)","Ханкинтатукку Оу"" (""Hankintatukku Oy""), Lehtolankatu 18, 03600 Karkkila (Финляндия)",RU.77.99.11.003.Е.000895.09.10 от 10.09.2010,"При необходимости прием можно повторить. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Срок годности - 3 года. Хранить в сухом, недоступном для детей месте, при температуре не выше 25°С.",иностранное,"индивидуальная непереносимость компонентов, беременность, кормление грудью",36,2010,много,вит,NaN,пнжк,NaN,фенольн,NaN,NaN,NaN,NaN,NaN,NaN,гидроксикор,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,таблетки,1-2 месяца,Природное (растительное),"Экстракта зелёного чая (Camellia sinensis - Камелия китайская), экстракт кожицы винограда (Винный виноград - Vitis Vinifera",NaN,NaN,взрослые,NaN,NaN,взрослым по 1 таблетке 2-3 раза в день во время еды.
2,"биологически активная добавка к пище ""Фемибион ® Наталкер I"" (""Femibion® Natalcare I"") (таблетки массой 609 мг±3% покрытые оболочкой)","""Мерк КгаА энд Ко Верк Шпитталь"", Хёссельгассе 20, А- 9800 Шпитталь/Драу, Австрия или ""Никомед Фарма Сп. з.о.о."", Ал. Иерозолимские 146 А, 02-305, Варшава, Польша под контролем ""Мерк Зельбстмедикацион ГмбХ, Pёсслерштрассе, 96, 64293 Дармштадт (""Merck Selbstmedikation GmbH"", Rosslerstrasse 96, 64293 Darmstadt) (ФРГ) Германия",RU.77.99.11.003.Е.000886.09.10 от 10.09.2010,"Хранить в сухом, недоступном для детей месте при температуре не выше 25°С. Противопоказания: индивидуальная непереносимость компонентов. Перед применением рекомендуется проконсультироваться с врачом.",иностранное,индивидуальная непереносимость компонентов,24,2010,2,вит,элементы,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,беременные,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,таблетки,": женщинам, планирующим беременность, и беременным до конца 12-й недели беременности по 1 таблетке 1 раз в день во время еды, запивая водой. Срок годности - 24 месяца",Синтетическое,NaN,NaN,NaN,взрослые,женщины,NaN,"женщинам, планирующим беременность, и беременным до конца 12-й недели беременности по 1 таблетке 1 раз в день во время еды, запивая водой."
3,"биологически активная добавка к пище ""Неогален (Neogalen). СЛИМ КОД. Комплекс"" (капсулы массой 500 мг)","продукция изготовлена ООО ""КоролёвФарм"", 121609, г. Москва, ул. Крылатские холмы, д.1, кв.422 (адрес производства: 141070, Московская область, г.Королёв, ул. Пионерская, д.4) (Российская Федерация)",RU.77.99.11.003.Е.001040.09.10 от 14.09.2010,"Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Срок годности - 2 года. Хранить в сухом, защищенном от света и недоступном для детей месте, при температуре не выше 25°С.",отечественное,"индивидуальная непереносимость компонентов, беременность, кормление грудью",24,2010,много,вит,NaN,NaN,аминокислоты,фенольн,NaN,NaN,NaN,NaN,NaN,ест,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,жкт,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,капсулы,1 месяц,Природное (растительное),"Экстракт травы гарцинии камбоджийской (Garcīnia gūmmi-gūtta - Гарци́ния камбоджи́йская), экстракт листьев матэ (Падуб парагва́йский - Ilex paraguariénsis), экстракт виноградных косточек, алоэ вера гель (Алоэ вера - Aloë vera)",NaN,NaN,взрослые,NaN,NaN,взрослым по 1 капсуле 3 раза в день во время еды.
4,"биологически активная добавка к пище ""КРЕСТИНОЛ"" (капсулы по 350 мг)","ЗАО ""Пекталь"", 193019, г. Санкт-Петербург, ул. Бехтерева, д.1 (Российская Федерация)",RU.77.99.11.003.Е.001573.10.10 от 05.10.2010,"После 10 дневного перерыва рекомендуется повторный прием. Возможны повторные приемы в течение года. Срок годности - 2 года. Хранить в сухом, защищенном от света и недоступном для детей месте, при температуре не выше 25°С. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением необходимо проконсультироваться с врачом.",отечественное,"индивидуальная непереносимость компонентов, беременность, кормление грудью",24,2010,много,вит,NaN,NaN,NaN,фенольн,NaN,NaN,NaN,NaN,NaN,ест,NaN,NaN,дуб,NaN,NaN,NaN,NaN,NaN,NaN,почки,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,капсулы,20 дней,Природное (растительное),"Экстракт брокколи (Капуста огородная - Brassica oleracea), экстракт сои (Соя культурная - Glycine max), экстракт листьев бадана (Бадан толстолистный - Bergenia crassifolia), экстракт корней дягиля лекарственного (Дягиль лекарственный - Angеlica archangelica) , экстракт корней цимицифуги (Клопогон кистевидный - Cimicifuga racemosa), экстракт травы боровой матки (Орти́лия однобо́кая - Orthília secúnda)",NaN,NaN,взрослые,NaN,NaN,взрослым по 1 капсуле 1 раз в день во время еды.

Посмотрим имена столбцов

In [71]:
print("Имена колонок:")
for c in df.columns[:]:
    print("-", c)

Имена колонок:
- наименование
- изготовитель
- номер_свидетельства_и_дата
- этикетка
- происхождение
- противопоказания
- срок_годности
- год_регистрации
- количество_групп_компонентов
- пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты
- пищевые_вещества_макро_и_микроэлементы
- пищевые_вещества_жиры_жироподобные_вещества_и_их_производные
- пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты
- минорные_компоненты_растений_фенольные_соединения
- минорные_компоненты_растений_алкалоиды
- пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы
- пищевые_вещества_углеводы_и_продукты_их_переработки
- минорные_компоненты_растений_сапонины
- минорные_компоненты_растений_терпеноиды
- минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма
- минорные_компоненты_растений_гидроксикоричные_кислоты
- минорные_компоненты_растений_ферменты
- минорные_компоненты_растений_дубильные_вещества
- минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты
- система_органов_для_беременных_кормящих_и_планирующих_беременность
- система_органов_костно_мышечная_система
- система_органов_нервная_система
- система_органов_иммунная_система
- система_органов_пищеварительный_тракт_и_обмен_веществ
- система_органов_мочеполовая_система
- система_органов_дерматологические_бад
- система_органов_органы_чувств
- система_органов_сердечно_сосудистая_система
- система_органов_противоопухолевые_бад
- система_органов_противопаразитарные_бад
- система_органов_дыхательная_система
- система_органов_кровь_и_система_кроветворения
- система_органов_противомикробные_бад
- форма_выпуска
- продолжительность_приема
- система_органов_происхождение_природное_синтетическое
- сырье
- группа_населения_предназначен_для_детей
- группа_населения_возраст_детей
- группа_населения_предназначен_для_взрослых
- группа_населения_пол
- группа_населения_пожилые
- рекомендации_по_применению

Посмотрим количество уникальных значений в каждом из столбцов

In [72]:
for col in df.columns:
    print(col, len(df[col].unique().tolist()))

наименование 4154
изготовитель 1634
номер_свидетельства_и_дата 4222
этикетка 3341
происхождение 2
противопоказания 2952
срок_годности 23
год_регистрации 14
количество_групп_компонентов 4
пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты 2
пищевые_вещества_макро_и_микроэлементы 2
пищевые_вещества_жиры_жироподобные_вещества_и_их_производные 3
пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты 2
минорные_компоненты_растений_фенольные_соединения 2
минорные_компоненты_растений_алкалоиды 2
пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы 2
пищевые_вещества_углеводы_и_продукты_их_переработки 2
минорные_компоненты_растений_сапонины 2
минорные_компоненты_растений_терпеноиды 2
минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма 2
минорные_компоненты_растений_гидроксикоричные_кислоты 2
минорные_компоненты_растений_ферменты 2
минорные_компоненты_растений_дубильные_вещества 2
минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты 2
система_органов_для_беременных_кормящих_и_планирующих_беременность 2
система_органов_костно_мышечная_система 2
система_органов_нервная_система 2
система_органов_иммунная_система 2
система_органов_пищеварительный_тракт_и_обмен_веществ 2
система_органов_мочеполовая_система 2
система_органов_дерматологические_бад 2
система_органов_органы_чувств 2
система_органов_сердечно_сосудистая_система 2
система_органов_противоопухолевые_бад 2
система_органов_противопаразитарные_бад 2
система_органов_дыхательная_система 4
система_органов_кровь_и_система_кроветворения 2
система_органов_противомикробные_бад 4
форма_выпуска 33
продолжительность_приема 921
система_органов_происхождение_природное_синтетическое 14
сырье 2724
группа_населения_предназначен_для_детей 2
группа_населения_возраст_детей 12
группа_населения_предназначен_для_взрослых 2
группа_населения_пол 3
группа_населения_пожилые 2
рекомендации_по_применению 603

Посмотрим уникальные значения, если их в столбце меньше 5

In [73]:
for col in df.columns:
    if len(df[col].unique().tolist())<5:
        print(col, df[col].unique().tolist())

происхождение ['иностранное', 'отечественное']
количество_групп_компонентов [3, 'много', 2, 1]
пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты ['вит', nan]
пищевые_вещества_макро_и_микроэлементы ['элементы', nan]
пищевые_вещества_жиры_жироподобные_вещества_и_их_производные [nan, 'пнжк', 'стеран']
пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты [nan, 'аминокислоты']
минорные_компоненты_растений_фенольные_соединения ['фенольн', nan]
минорные_компоненты_растений_алкалоиды [nan, 'алкалоиды']
пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы [nan, 'пробиотики']
пищевые_вещества_углеводы_и_продукты_их_переработки [nan, 'полисахариды']
минорные_компоненты_растений_сапонины [nan, 'сапонины']
минорные_компоненты_растений_терпеноиды [nan, 'терпен']
минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма [nan, 'ест']
минорные_компоненты_растений_гидроксикоричные_кислоты [nan, 'гидроксикор']
минорные_компоненты_растений_ферменты [nan, 'ферменты']
минорные_компоненты_растений_дубильные_вещества [nan, 'дуб']
минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты [nan, 'цеолиты']
система_органов_для_беременных_кормящих_и_планирующих_беременность [nan, 'беременные']
система_органов_костно_мышечная_система [nan, 'суставы']
система_органов_нервная_система [nan, 'нервная']
система_органов_иммунная_система ['иммунитет', nan]
система_органов_пищеварительный_тракт_и_обмен_веществ [nan, 'жкт']
система_органов_мочеполовая_система [nan, 'почки']
система_органов_дерматологические_бад [nan, 'кожа']
система_органов_органы_чувств [nan, 'глаза']
система_органов_сердечно_сосудистая_система [nan, 'сердце']
система_органов_противоопухолевые_бад [nan, 'онко']
система_органов_противопаразитарные_бад [nan, 'паразиты']
система_органов_дыхательная_система [nan, 'легкие', 'кашель', 'дых']
система_органов_кровь_и_система_кроветворения [nan, 'кровь']
система_органов_противомикробные_бад [nan, 'бактерия', 'гриб', 'вирус']
группа_населения_предназначен_для_детей [nan, 'дети']
группа_населения_предназначен_для_взрослых ['взрослые', nan]
группа_населения_пол [nan, 'женщины', 'мужчины']
группа_населения_пожилые [nan, 'пожилые']

Посмотрим процент пустых значений (missing, NaN, undefined) в столбцах

In [74]:
num_rows = len(df)

for col in df.columns:
    missing_percent = (((df[col].isna().sum())/num_rows)*100).round(2)
    print(f"{col}, {missing_percent}%")

наименование, 0.0%
изготовитель, 0.02%
номер_свидетельства_и_дата, 0.0%
этикетка, 0.0%
происхождение, 0.0%
противопоказания, 0.0%
срок_годности, 0.0%
год_регистрации, 0.0%
количество_групп_компонентов, 0.0%
пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты, 53.11%
пищевые_вещества_макро_и_микроэлементы, 70.87%
пищевые_вещества_жиры_жироподобные_вещества_и_их_производные, 90.53%
пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты, 86.46%
минорные_компоненты_растений_фенольные_соединения, 64.79%
минорные_компоненты_растений_алкалоиды, 95.48%
пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы, 95.6%
пищевые_вещества_углеводы_и_продукты_их_переработки, 88.63%
минорные_компоненты_растений_сапонины, 93.96%
минорные_компоненты_растений_терпеноиды, 94.32%
минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма, 94.55%
минорные_компоненты_растений_гидроксикоричные_кислоты, 97.47%
минорные_компоненты_растений_ферменты, 98.89%
минорные_компоненты_растений_дубильные_вещества, 93.99%
минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты, 99.31%
система_органов_для_беременных_кормящих_и_планирующих_беременность, 99.46%
система_органов_костно_мышечная_система, 87.12%
система_органов_нервная_система, 77.72%
система_органов_иммунная_система, 65.66%
система_органов_пищеварительный_тракт_и_обмен_веществ, 71.3%
система_органов_мочеполовая_система, 90.43%
система_органов_дерматологические_бад, 89.08%
система_органов_органы_чувств, 96.66%
система_органов_сердечно_сосудистая_система, 86.72%
система_органов_противоопухолевые_бад, 99.24%
система_органов_противопаразитарные_бад, 99.36%
система_органов_дыхательная_система, 95.78%
система_органов_кровь_и_система_кроветворения, 98.06%
система_органов_противомикробные_бад, 98.53%
форма_выпуска, 0.0%
продолжительность_приема, 0.0%
система_органов_происхождение_природное_синтетическое, 0.0%
сырье, 25.69%
группа_населения_предназначен_для_детей, 83.99%
группа_населения_возраст_детей, 83.99%
группа_населения_предназначен_для_взрослых, 3.53%
группа_населения_пол, 96.99%
группа_населения_пожилые, 99.79%
рекомендации_по_применению, 0.0%

# Бинаризация

In [95]:
df_copy= df.copy(deep=True)
def binarize(df, columns, method="values", positive_values=None):
    """
    бинаризация:
    - method="values": значение → 1, если оно в positive_values
    """

    for col in columns:
        # Приводим столбец к строке и чистим
        cleaned = df[col].astype(str).str.strip().str.lower()
        if method == "values":
            target = [v.lower() for v in positive_values]
            df[col] = cleaned.isin(target).astype(int)
    return df

In [96]:
df_copy=binarize(df_copy,["происхождение"],method="values",positive_values=["отечественное"])
#df_copy.head()

In [97]:
forms_release = [
    'таблетки', 'капсулы', 'растворы', 'порошок', 'сбор',
    'пастилки', 'драже', 'пилюли', 'гели',
    'гранулы','желе','леденцы','пасты','плитки','суспензия'
]
groups = {
    'твёрдые': ['таблетки', 'капсулы', 'пилюли', 'драже', 'пастилки', 'плитки', 'гранулы', 'леденцы','порошок'],
    'полутвёрдые': ['гели', 'пасты', 'желе'],
    'жидкие': ['растворы', 'суспензия'],
    'сборы': ['сбор']
}
df_copy['форма_выпуска'] = (
    df_copy['форма_выпуска']
    .astype(str)
    .str.lower()
    .str.replace(r'[^а-яa-z, ]', '', regex=True)
)
for form in forms_release:
    df_copy[form] = df_copy['форма_выпуска'].apply(
        lambda x: 1 if form in x else 0
    )
for cat, forms in groups.items():
    df_copy[cat] = df_copy[forms].max(axis=1)
df_copy = df_copy.drop(columns=forms_release)
df_copy = df_copy.drop('форма_выпуска', axis=1)

# Бинаризация Пищевые вещества

In [108]:
food_materials = [
    'пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты','пищевые_вещества_макро_и_микроэлементы',
    'пищевые_вещества_жиры_жироподобные_вещества_и_их_производные','пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты',
    'пищевые_вещества_углеводы_и_продукты_их_переработки'
]
bins = [
    'вит','элементы','пнжк','аминокислоты','полисахариды'
]
for mat in food_materials:
  for bin in bins:
    df_copy = binarize(df_copy,[mat],method="values",positive_values=[bin])

# Бинаризация Минорные компоненты

In [112]:
copm = [
    'минорные_компоненты_растений_фенольные_соединения','минорные_компоненты_растений_алкалоиды',
    'минорные_компоненты_растений_сапонины','минорные_компоненты_растений_терпеноиды',
    'минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма',
    'минорные_компоненты_растений_гидроксикоричные_кислоты',
    'минорные_компоненты_растений_ферменты',
    'минорные_компоненты_растений_дубильные_вещества'
]
bins = [
    'фенольн','алкалоиды','сапонины','терпен','ест','гидроксикор','ферменты','дуб'
]
for mat in copm:
  for bin in bins:
    df_copy = binarize(df_copy,[mat],method="values",positive_values=[bin])

# Бинаризация Пробиотики,Минералы

In [113]:
copm = [
    'пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы',
    'минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты'
]
bins = [
    'пробиотики','цеолиты'
]
for mat in copm:
  for bin in bins:
    df_copy = binarize(df_copy,[mat],method="values",positive_values=[bin])

# Бинаризация Система органов

In [114]:
copm = [
    'система_органов_для_беременных_кормящих_и_планирующих_беременность','система_органов_костно_мышечная_система',
    'система_органов_нервная_система','система_органов_иммунная_система',
    'система_органов_пищеварительный_тракт_и_обмен_веществ',
    'система_органов_мочеполовая_система','система_органов_дерматологические_бад',
    'система_органов_органы_чувств','система_органов_сердечно_сосудистая_система',
    'система_органов_противоопухолевые_бад','система_органов_противопаразитарные_бад',
    'система_органов_кровь_и_система_кроветворения'
]
bins = [
    'беременные','суставы','нервная','иммунитет','жкт','почки','кожа','глаза','сердце','онко',
    'паразиты','кровь'
]
for mat in copm:
  for bin in bins:
    df_copy = binarize(df_copy,[mat],method="values",positive_values=[bin])

# Бинаризация Группа населения

In [115]:
copm = [
    'группа_населения_предназначен_для_детей',
    'группа_населения_предназначен_для_взрослых',
    'группа_населения_пол',
    'группа_населения_пожилые'
]
bins = [
    'дети','взрослые','мужчины','пожилые'
]
for mat in copm:
  for bin in bins:
    df_copy = binarize(df_copy,[mat],method="values",positive_values=[bin])

In [116]:
df_copy.head()

,наименование,изготовитель,номер_свидетельства_и_дата,этикетка,происхождение,противопоказания,срок_годности,год_регистрации,количество_групп_компонентов,пищевые_вещества_витамины_витаминоподобные_вещества_и_коферменты,пищевые_вещества_макро_и_микроэлементы,пищевые_вещества_жиры_жироподобные_вещества_и_их_производные,пищевые_вещества_белки_пептиды_аминокислоты_нуклеиновые_кислоты,минорные_компоненты_растений_фенольные_соединения,минорные_компоненты_растений_алкалоиды,пробиотики_в_монокультурах_и_ассоциациях_пробиотические_микроорганизмы,пищевые_вещества_углеводы_и_продукты_их_переработки,минорные_компоненты_растений_сапонины,минорные_компоненты_растений_терпеноиды,минорные_компоненты_растений_естественные_метаболиты_и_стимуляторы_метаболизма,минорные_компоненты_растений_гидроксикоричные_кислоты,минорные_компоненты_растений_ферменты,минорные_компоненты_растений_дубильные_вещества,минеральные_и_минерало_органические_природные_субстанции_цеолиты_и_гуминовые_кислоты,система_органов_для_беременных_кормящих_и_планирующих_беременность,система_органов_костно_мышечная_система,система_органов_нервная_система,система_органов_иммунная_система,система_органов_пищеварительный_тракт_и_обмен_веществ,система_органов_мочеполовая_система,система_органов_дерматологические_бад,система_органов_органы_чувств,система_органов_сердечно_сосудистая_система,система_органов_противоопухолевые_бад,система_органов_противопаразитарные_бад,система_органов_дыхательная_система,система_органов_кровь_и_система_кроветворения,система_органов_противомикробные_бад,продолжительность_приема,система_органов_происхождение_природное_синтетическое,сырье,группа_населения_предназначен_для_детей,группа_населения_возраст_детей,группа_населения_предназначен_для_взрослых,группа_населения_пол,группа_населения_пожилые,рекомендации_по_применению,твёрдые,полутвёрдые,жидкие,сборы
0,"биологически активная добавка к пище ""ВитаФин"" (""VitaFin"") (таблетки массой 700 мг)","Ханкинтатукку Оу"" (""Hankintatukku Oy""), Lehtolankatu 18, 03600 Karkkila (Финляндия)",RU.77.99.11.003.Е.000894.09.10 от 10.09.2010,"При необходимости прием можно повторить. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Лицам с заболеваниями щитовидной микроэлементыы рекомендуется проконсультироваться с врачом-эндокринологом. Срок годности - 3 года. Хранить в сухом, недоступном для детей месте, при температуре не выше 25°С.",0,"индивидуальная непереносимость компонентов, беременность, кормление грудью",36,2010,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,1-2 месяца,Природное (растительное),"Экстракта зелёного чая (Camellia sinensis - Камелия китайская), экстракт кожицы винограда (Винный виноград - Vitis Vinifera",0,NaN,0,0,0,взрослым по 1-2 таблетки в день во время еды.,1,0,0,0
1,"биологически активная добавка к пище ""Гепаплант"" (""Hepaplant"") (таблетки массой 1000 мг)","Ханкинтатукку Оу"" (""Hankintatukku Oy""), Lehtolankatu 18, 03600 Karkkila (Финляндия)",RU.77.99.11.003.Е.000895.09.10 от 10.09.2010,"При необходимости прием можно повторить. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Срок годности - 3 года. Хранить в сухом, недоступном для детей месте, при температуре не выше 25°С.",0,"индивидуальная непереносимость компонентов, беременность, кормление грудью",36,2010,много,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,1-2 месяца,Природное (растительное),"Экстракта зелёного чая (Camellia sinensis - Камелия китайская), экстракт кожицы винограда (Винный виноград - Vitis Vinifera",0,NaN,0,0,0,взрослым по 1 таблетке 2-3 раза в день во время еды.,1,0,0,0
2,"биологически активная добавка к пище ""Фемибион ® Наталкер I"" (""Femibion® Natalcare I"") (таблетки массой 609 мг±3% покрытые оболочкой)","""Мерк КгаА энд Ко Верк Шпитталь"", Хёссельгассе 20, А- 9800 Шпитталь/Драу, Австрия или ""Никомед Фарма Сп. з.о.о."", Ал. Иерозолимские 146 А, 02-305, Варшава, Польша под контролем ""Мерк Зельбстмедикацион ГмбХ, Pёсслерштрассе, 96, 64293 Дармштадт (""Merck Selbstmedikation GmbH"", Rosslerstrasse 96, 64293 Darmstadt) (ФРГ) Германия",RU.77.99.11.003.Е.000886.09.10 от 10.09.2010,"Хранить в сухом, недоступном для детей месте при температуре не выше 25°С. Противопоказания: индивидуальная непереносимость компонентов. Перед применением рекомендуется проконсультироваться с врачом.",0,индивидуальная непереносимость компонентов,24,2010,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,": женщинам, планирующим беременность, и беременным до конца 12-й недели беременности по 1 таблетке 1 раз в день во время еды, запивая водой. Срок годности - 24 месяца",Синтетическое,NaN,0,NaN,0,0,0,"женщинам, планирующим беременность, и беременным до конца 12-й недели беременности по 1 таблетке 1 раз в день во время еды, запивая водой.",1,0,0,0
3,"биологически активная добавка к пище ""Неогален (Neogalen). СЛИМ КОД. Комплекс"" (капсулы массой 500 мг)","продукция изготовлена ООО ""КоролёвФарм"", 121609, г. Москва, ул. Крылатские холмы, д.1, кв.422 (адрес производства: 141070, Московская область, г.Королёв, ул. Пионерская, д.4) (Российская Федерация)",RU.77.99.11.003.Е.001040.09.10 от 14.09.2010,"Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением рекомендуется проконсультироваться с врачом. Срок годности - 2 года. Хранить в сухом, защищенном от света и недоступном для детей месте, при температуре не выше 25°С.",1,"индивидуальная непереносимость компонентов, беременность, кормление грудью",24,2010,много,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,1 месяц,Природное (растительное),"Экстракт травы гарцинии камбоджийской (Garcīnia gūmmi-gūtta - Гарци́ния камбоджи́йская), экстракт листьев матэ (Падуб парагва́йский - Ilex paraguariénsis), экстракт виноградных косточек, алоэ вера гель (Алоэ вера - Aloë vera)",0,NaN,0,0,0,взрослым по 1 капсуле 3 раза в день во время еды.,1,0,0,0
4,"биологически активная добавка к пище ""КРЕСТИНОЛ"" (капсулы по 350 мг)","ЗАО ""Пекталь"", 193019, г. Санкт-Петербург, ул. Бехтерева, д.1 (Российская Федерация)",RU.77.99.11.003.Е.001573.10.10 от 05.10.2010,"После 10 дневного перерыва рекомендуется повторный прием. Возможны повторные приемы в течение года. Срок годности - 2 года. Хранить в сухом, защищенном от света и недоступном для детей месте, при температуре не выше 25°С. Противопоказания: индивидуальная непереносимость компонентов, беременность, кормление грудью. Перед применением необходимо проконсультироваться с врачом.",1,"индивидуальная непереносимость компонентов, беременность, кормление грудью",24,2010,много,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,20 дней,Природное (растительное),"Экстракт брокколи (Капуста огородная - Brassica oleracea), экстракт сои (Соя культурная - Glycine max), экстракт листьев бадана (Бадан толстолистный - Bergenia crassifolia), экстракт корней дягиля лекарственного (Дягиль лекарственный - Angеlica archangelica) , экстракт корней цимицифуги (Клопогон кистевидный - Cimicifuga racemosa), экстракт травы боровой матки (Орти́лия однобо́кая - Orthília secúnda)",0,NaN,0,0,0,взрослым по 1 капсуле 1 раз в день во время еды.,1,0,0,0

Сохранение изменений

In [117]:
!pip -q install jupytext nbstripout

from google.colab import drive
drive.mount('/content/drive')

NOTEBOOK = "/content/drive/MyDrive/Colab Notebooks/3311_bajmuhamedov_arshin_pasechny_practice_BAD.ipynb"

cfg = '''formats = "ipynb,py:percent"
cell_metadata_filter = "-all"
notebook_metadata_filter = "kernelspec,jupytext"
'''
with open("/content/.jupytext.toml", "w", encoding="utf-8") as f:
    f.write(cfg)

import os, pathlib, time, textwrap, subprocess, json
ipynb_path = pathlib.Path(NOTEBOOK)
py_path = ipynb_path.with_suffix(".py")

if not ipynb_path.exists():
    raise FileNotFoundError(f"Не найден .ipynb: {ipynb_path}")

print("IPYNB:", ipynb_path)
print("PY:", py_path)

!nbstripout "{NOTEBOOK}"

if py_path.exists():
    py_path.unlink()
!jupytext --to py:percent "{NOTEBOOK}"

import datetime
stat = py_path.stat()
print("\nОбновлён .py:", py_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
IPYNB: /content/drive/MyDrive/Colab Notebooks/3311_bajmuhamedov_arshin_pasechny_practice_BAD.ipynb
PY: /content/drive/MyDrive/Colab Notebooks/3311_bajmuhamedov_arshin_pasechny_practice_BAD.py
[jupytext] Reading /content/drive/MyDrive/Colab Notebooks/3311_bajmuhamedov_arshin_pasechny_practice_BAD.ipynb in format ipynb
[jupytext] Writing '/content/drive/MyDrive/Colab Notebooks/3311_bajmuhamedov_arshin_pasechny_practice_BAD.py' in format py:percent

Обновлён .py: /content/drive/MyDrive/Colab Notebooks/3311_bajmuhamedov_arshin_pasechny_practice_BAD.py